EXECUTABLE=exercise_1_9
SOURCE=main.go
OUTPUT=out.gif

# Build app
$(EXECUTABLE): main.go
	go build -o $(EXECUTABLE) $(main.go)
	./$(EXECUTABLE) http://gopl.io

run:
	./$(EXECUTABLE) http://gopl.ioooomake