HOME=/Users/rodrigosilveira/projects/go-kernighan/bin/
EXECUTABLE=$(HOME)server1
SOURCE=main.go
#OUTPUT=out.gif

# Build app
$(EXECUTABLE): main.go
	go build -o $(EXECUTABLE) $(main.go)

run:
	$(EXECUTABLE) &
